import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Movie-Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (<>
        <Head>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        {children}
        <Footer/>
        </>
  );
}
